export const CognitoSignInNextSteps = {
  DONE: 'DONE',
  CONFIRM_SIGN_IN_WITH_NEW_PASSWORD_REQUIRED: 'CONFIRM_SIGN_IN_WITH_NEW_PASSWORD_REQUIRED',
  CONFIRM_SIGN_IN_WITH_CUSTOM_CHALLENGE: 'CONFIRM_SIGN_IN_WITH_CUSTOM_CHALLENGE',
  CONFIRM_SIGN_IN_WITH_TOTP_CODE: 'CONFIRM_SIGN_IN_WITH_TOTP_CODE',
  CONTINUE_SIGN_IN_WITH_TOTP_SETUP: 'CONTINUE_SIGN_IN_WITH_TOTP_SETUP',
  CONFIRM_SIGN_IN_WITH_SMS_CODE: 'CONFIRM_SIGN_IN_WITH_SMS_CODE',
  CONTINUE_SIGN_IN_WITH_MFA_SELECTION: 'CONTINUE_SIGN_IN_WITH_MFA_SELECTION',
  RESET_PASSWORD: 'RESET_PASSWORD',
  CONFIRM_SIGN_UP: 'CONFIRM_SIGN_UP',
};
